#include "includes/ft_printf.h"
#include <stdio.h>

int	main()
{
	int a;
	int *b;
	long c;

	/*

ft_printf("----------------------------------------------------------\n");
	ft_printf("--- CHARS ---\n");

	b = ft_printf("%5c%3c\n", 'c', 'd');
	printf("-> %d\n", b);
	a = printf("%5c%3c\n", 'c', 'd');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*c\n", 5, 'H');
	printf("-> %d\n", b);
	a = printf("%*c\n", 5, 'H');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*c%c-%c\n", -10, 'c', 'r', 't');
	printf("-> %d\n", b);
	a = printf("%*c%c-%c\n", -10, 'c', 'r', 't');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%c", 'a');
	printf("-> %d\n", b);
	a = printf("%c", 'a');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%1c", '-');
	printf("-> %d\n", b);
	a = printf("%1c", '-');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*c", 12, '0');
	printf("-> %d\n", b);
	a = printf("%*c", 12, '0');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-*c", 12, '-');
	printf("-> %d\n", b);
	a = printf("%-*c", 12, '-');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*c", 12, '%');
	printf("-> %d\n", b);
	a = printf("%*c", 12, '%');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-*c", 12, 'a');
	printf("-> %d\n", b);
	a = printf("%-*c", 12, 'a');
	printf("-> %d \n", a);
ft_printf("\n");


ft_printf("----------------------------------------------------------\n");
	ft_printf("--- CAS D'ERREURS ---\n");

	ft_printf("D: Doit afficher du vide -> '%.0d'\n", 0);
	printf("O: Doit afficher du vide -> '%.0d'\n", 0);
	ft_printf("D: Doit afficher du vide -> '%.d'\n", 0);
	printf("O: Doit afficher du vide -> '%.d'\n", 0);
	ft_printf("D: Doit afficher du vide -> '%.0u'\n", 0);
	printf("O: Doit afficher du vide -> '%.0u'\n", 0);
	ft_printf("D: Doit afficher du vide -> '%.u'\n", 0);
	printf("O: Doit afficher du vide -> '%.u'\n", 0);
	ft_printf("D: Doit afficher du vide -> '%.0x'\n", 0);
	printf("O: Doit afficher du vide -> '%.0x'\n", 0);
	ft_printf("D: Doit afficher du vide -> '%.x'\n", 0);
	printf("O: Doit afficher du vide -> '%.x'\n", 0);
	ft_printf("D: Doit afficher du vide -> '%.0s'\n", "");
	printf("O: Doit afficher du vide -> '%.0s'\n", "");
	ft_printf("D: Doit afficher du vide -> '%.s'\n", "");
	printf("O: Doit afficher du vide -> '%.s'\n", "");
	ft_printf("\n");

	
ft_printf("----------------------------------------------------------\n");
	ft_printf("--- DOUBLE POURCENT ---\n");

	ft_printf("D: %%\n");
	printf("O: %%\n");
	ft_printf("D: %-020%\n");
	printf("O: %-020%\n");
	ft_printf("D: a%%a\n", 25);
	printf("O: a%%a\n", 25);
	ft_printf("D: %%-%%-%d%% %%\n", 5);
	printf("O: %%-%%-%d%% %%\n", 5);
	ft_printf("\n");


ft_printf("----------------------------------------------------------\n");
	ft_printf("--- POINTEURS ---\n");

	b = ft_printf("%-22.5p\n", &a);
	printf("-> %d\n", b);
	a = printf("%-22.5p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%022.5p\n", &b);
	printf("-> %d\n", b);
	a = printf("%022.5p\n", &b);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%022p\n", &a);
	printf("-> %d\n", b);
	a = printf("%022p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%22p\n", &a);
	printf("-> %d\n", b);
	a = printf("%22p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-22p\n", &a);
	printf("-> %d\n", b);
	a = printf("%-22p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%5.22p\n", &a);
	printf("-> %d\n", b);
	a = printf("%5.22p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%23.22p\n", &a);
	printf("-> %d\n", b);
	a = printf("%23.22p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%5.3p\n", &a);
	printf("-> %d\n", b);
	a = printf("%5.3p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%23.3p\n", &a);
	printf("-> %d\n", b);
	a = printf("%23.3p\n", &a);
	printf("-> %d \n", a);
ft_printf("\n");
*/	b = ft_printf("%p", 0);
	printf("-> %d\n", b);
	printf("0x0-> 3\n");
ft_printf("\n");
/*	b = ft_printf("%-*p", 10, (void *)209590960);
	printf("-> %d\n", b);
	a = printf("%-*p", 10, (void *)209590960);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-*p", 10, (void *)209590960);
	printf("-> %d\n", b);
	a = printf("%-*p", 10, (void *)209590960);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-*p", 11, (void *)209590960);
	printf("-> %d\n", b);
	a = printf("%-*p", 11, (void *)209590960);
	printf("-> %d \n", a);
ft_printf("\n");


ft_printf("----------------------------------------------------------\n");
	ft_printf("--- INTS ---\n");

	ft_printf("D: %-12.5d\n", -5);
	printf("O: %-12.5d\n", -5);
	ft_printf("D: %012.5d\n", -5);
	printf("O: %012.5d\n", -5);
	ft_printf("D: %012d\n", -5);
	printf("O: %012d\n", -5);
	ft_printf("D: %12d\n", -5);
	printf("O: %12d\n", -5);
	ft_printf("D: %-12d\n", -5);
	printf("O: %-12d\n", -5);
	ft_printf("D: %05.12d\n", -5);
	printf("O: %05.12d\n", -5);
	ft_printf("D: %13.12d\n", -5);
	printf("O: %13.12d\n", -5);
	ft_printf("D: %*d\n", -10, 5);
	printf("O: %*d\n", -10, 5);
	ft_printf("\n");


ft_printf("----------------------------------------------------------\n");
	ft_printf("--- UNSIGNED INTS ---\n");

	b = ft_printf("%-12.5u\n", 5);
	printf("-> %d\n", b);
	a = printf("%-12.5u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%012.5u\n", 5);
	printf("-> %d\n", b);
	a = printf("%012.5u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%012u\n", 5);
	printf("-> %d\n", b);
	a = printf("%012u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%12u\n", 5);
	printf("-> %d\n", b);
	a = printf("%12u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-12u\n", 5);
	printf("-> %d\n", b);
	a = printf("%-12u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%05.12u\n", 5);
	printf("-> %d\n", b);
	a = printf("%05.12u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%13.12u\n", 5);
	printf("-> %d\n", b);
	a = printf("%13.12u\n", 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u\n", -10, 5);
	printf("-> %d\n", b);
	a = printf("%*u\n", -10, 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, 8);
	printf("-> %d\n", b);
	a = printf("%*u", -1, 8);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, -12);
	printf("-> %d\n", b);
	a = printf("%*u", -1, -12);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, 123456789);
	printf("-> %d\n", b);
	a = printf("%*u", -1, 123456789);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, 0);
	printf("-> %d\n", b);
	a = printf("%*u", -1, 0);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, -12345678);
	printf("-> %d\n", b);
	a = printf("%*u", -1, -12345678);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, 'a');
	printf("-> %d\n", b);
	a = printf("%*u", -1, 'a');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, 2147483647);
	printf("-> %d\n", b);
	a = printf("%*u", -1, 2147483647);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*u", -1, -2147483648);
	printf("-> %d\n", b);
	a = printf("%*u", -1, -2147483648);
	printf("-> %d \n", a);
ft_printf("\n");


ft_printf("----------------------------------------------------------\n");
	ft_printf("--- HEXA ---\n");

	b = ft_printf("%-12.5x", -125);
	printf("-> %d\n", b);
	a = printf("%-12.5x", -125);
	printf("-> %d \n", a);
	ft_printf("\n");
ft_printf("\n");
	b = ft_printf("%012.5x", -125);
	printf("-> %d\n", b);
	a = printf("%012.5x", -125);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%012x", -125);
	printf("-> %d\n", b);
	a = printf("%012x", -125);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%12x", -125);
	printf("-> %d\n", b);
	a = printf("%12x", -125);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%-12x", -125);
	printf("-> %d\n", b);
	a = printf("%-12x", -125);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%05.12x", -125);
	printf("-> %d\n", b);
	a = printf("%05.12x", -125);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%13.12x", -125);
	printf("-> %d\n", b);
	a = printf("%13.12x", -125);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x\n", -10, 5);
	printf("-> %d\n", b);
	a = printf("%*x\n", -10, 5);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, 8);
	printf("-> %d\n", b);
	a = printf("%*x", -1, 8);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, 8);
	printf("-> %d\n", b);
	a = printf("%*X", -1, 8);
	printf("-> %d \n", a);
ft_printf("\n");
b = ft_printf("%*x", -1, -12);
	printf("-> %d\n", b);
	a = printf("%*x", -1, -12);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, -12);
	printf("-> %d\n", b);
	a = printf("%*X", -1, -12);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, 123456789);
	printf("-> %d\n", b);
	a = printf("%*x", -1, 123456789);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, 123456789);
	printf("-> %d\n", b);
	a = printf("%*X", -1, 123456789);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, 0);
	printf("-> %d\n", b);
	a = printf("%*x", -1, 0);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, 0);
	printf("-> %d\n", b);
	a = printf("%*X", -1, 0);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, -12345678);
	printf("-> %d\n", b);
	a = printf("%*x", -1, -12345678);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, -12345678);
	printf("-> %d\n", b);
	a = printf("%*X", -1, -12345678);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, 'a');
	printf("-> %d\n", b);
	a = printf("%*x", -1, 'a');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, 'a');
	printf("-> %d\n", b);
	a = printf("%*X", -1, 'a');
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, 2147483647);
	printf("-> %d\n", b);
	a = printf("%*x", -1, 2147483647);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, 2147483647);
	printf("-> %d\n", b);
	a = printf("%*X", -1, 2147483647);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*x", -1, -2147483648);
	printf("-> %d\n", b);
	a = printf("%*x", -1, -2147483648);
	printf("-> %d \n", a);
ft_printf("\n");
	b = ft_printf("%*X", -1, -2147483648);
	printf("-> %d\n", b);
	a = printf("%*X", -1, -2147483648);
	printf("-> %d \n", a);
ft_printf("\n");


ft_printf("----------------------------------------------------------\n");
	ft_printf("--- STRINGS ---\n");

	ft_printf("D: %015s\n", "Une phrase");
	printf("O: %015s\n", "Une phrase");
	ft_printf("D: %15s\n", "Une phrase");
	printf("O: %15s\n", "Une phrase");
	ft_printf("D: %-15s\n", "Une phrase");
	printf("O: %-15s\n", "Une phrase");
	ft_printf("D: %.4s%04.6s-%06s\n", "un ", "deux", "trois");
	printf("O: %.4s%04.6s-%06s\n", "un ", "deux", "trois");
	ft_printf("D: aaaaaaa-%13.12s\n", "string");
	printf("O: aaaaaaa-%13.12s\n", "string");
	ft_printf("D: %05.12s-aaaaaa\n", "string");
	printf("O: %05.12s-aaaaaa\n", "string");
	ft_printf("D: %015s\n", "Une phrase");
	printf("O: %015s\n", "Une phrase");
	ft_printf("D: Minus = 0 : %15s\n", "Une phrase");
	printf("O: Minus = 0 : %15s\n", "Une phrase");
	ft_printf("D: Minus = 1 : %-15s\n", "Une phrase");
	printf("O: Minus = 1 : %-15s\n", "Une phrase");
	ft_printf("D: Width = 1 : %1s\n", "Une phrase");
	printf("O: Width = 1 : %1s\n", "Une phrase");
	ft_printf("D: Precision .6 : '%.6s' Precision 8.6 : '%8.6s' Precision .1 : '%.1s'\n", "un", "deux", "trois");
	printf("O: Precision .6 : '%.6s' Precision 8.6 : '%8.6s' Precision .1 : '%.1s'\n", "un", "deux", "trois");
	ft_printf("D: Precision 1.2 : '%1.2s' Precision 2.1 : '%2.1s' Precision 2.6 : '%2.6s'\n", "un", "deux", "trois");
	printf("O: Precision 1.2 : '%1.2s' Precision 2.1 : '%2.1s' Precision 2.6 : '%2.6s'\n", "un", "deux", "trois");
	ft_printf("D: aaaaaaa-%12.12s-a\n", "string");
	printf("O: aaaaaaa-%12.12s-a\n", "string");
	ft_printf("D: %1.12s-aaaaaa\n", "string");
	printf("O: %1.12s-aaaaaa\n", "string");
	ft_printf("D: %*s\n", -10, "abc");
	printf("O: %*s\n", -10, "abc");
	ft_printf("\n");



*/
	ft_printf("--- ERREURS ---\n");
	b = ft_printf("%-2s", NULL);
	printf("-> %d\n", b);
	printf("(null)-> 6\n");
ft_printf("\n");
	b = ft_printf("%.s", NULL);
	printf("-> %d\n", b);
	printf("-> 0\n");
ft_printf("\n");
	b = ft_printf("%-4s", NULL);
	printf("-> %d\n", b);
	printf("(null)-> 6\n");
ft_printf("\n");
	b = ft_printf("%-2.4s", NULL);
	printf("-> %d\n", b);
	printf("(nul-> 4\n");
ft_printf("\n");
	b = ft_printf("%-8.12s", NULL);
	printf("-> %d\n", b);
	printf("(null)  -> 8\n");
ft_printf("\n");
	b = ft_printf("%3s", NULL);
	printf("-> %d\n", b);
	printf("(null)-> 6\n");
ft_printf("\n");
	b = ft_printf("%8s", NULL);
	printf("-> %d\n", b);
	printf("  (null)-> 8\n");
ft_printf("\n");
	b = ft_printf("%---2s", NULL);
	printf("-> %d\n", b);
	printf("(null)-> 6\n");
ft_printf("\n");
	b = ft_printf("%.*s", -2, NULL);
	printf("-> %d\n", b);
	printf("(null)-> 6\n");
ft_printf("\n");
	b = ft_printf("%.0s", NULL);
	printf("-> %d\n", b);
	printf("-> 0\n");
ft_printf("\n");
	b = ft_printf("%.1s", NULL);
	printf("-> %d\n", b);
	printf("(-> 1\n");
ft_printf("\n");
	b = ft_printf("%.4s", NULL);
	printf("-> %d\n", b);
	printf("(nul-> 4\n");
ft_printf("\n");
ft_printf("\n");

	return (0);
}
